server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Store
          uri: http://localhost:8082
          predicates:
            - Path=/pickups/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: OrderDetail
          uri: http://localhost:8084
          predicates:
            - Path=/orderDetails/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/pickups/** 
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: OrderDetail
          uri: http://orderDetail:8080
          predicates:
            - Path=/orderDetails/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
